name: Upload to Cloudflare R2
on:
  push:
    branches:
      - i18n
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to Cloudflare R2
        uses: AnimMouse/setup-rclone@main
        with:
          rclone_config: ${{ secrets.CF_RCLONE_CONFIG }} #base64
          version: latest

      - run: |
          rclone sync images/ r2:/vl3box/decoration/images/
          rclone sync index.json r2:/vl3box/decoration/index.json
          rclone sync honor/ r2:/vl3box/decoration/honor/
          rclone sync honor.json r2:/vl3box/decoration/honor.json
